# Generated by Django 6.0.2 on 2026-02-25 10:24

import apps.evidence.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_witnesstestimony_witnesstestimonyattachment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='evidence',
            new_name='evidence_ev_case_id_97293a_idx',
            old_name='evidence_ev_case_id_9f9eb0_idx',
        ),
        migrations.RenameIndex(
            model_name='evidence',
            new_name='evidence_ev_registe_3ea150_idx',
            old_name='evidence_ev_registe_3c8da3_idx',
        ),
        migrations.AlterField(
            model_name='witnesstestimonyattachment',
            name='file',
            field=models.FileField(upload_to=apps.evidence.models.evidence_attachment_upload_path),
        ),
    ]
