# Generated by Django 6.0.2 on 2026-02-25 23:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("evidence", "0003_initial_evidence"),
        ("evidence", "0008_evidencelink"),
    ]

    operations = []
